### PR TITLE
Add new emojis to `emojis.json`

### PR DESCRIPTION
**Pull request by drygdryg**
Added some emojis that I got from the Rocket.Chat web client, as well as flags of all countries.

### CODE REVIEW

**Comment by drygdryg** [comment]
When viewing commit https://github.com/verdigado/rocketchat2matrix/pull/23/commits/516ea6fcec0a6cd1d1909c19120f74e12c6c541d in a browser, `digit_`-prefixed emojis may look like ordinary ASCII numbers, but they are actually Unicode characters.
image

**Comment by HerHde** [comment]
> When viewing commit [516ea6f](https://github.com/verdigado/rocketchat2matrix/commit/516ea6fcec0a6cd1d1909c19120f74e12c6c541d) in a browser, `digit_`-prefixed emojis may look like ordinary ASCII numbers (it can be confusing), but they are actually Unicode characters.

Why are you replacing them? Our RC shows them as it was before.

**Comment by drygdryg** [comment]
> Why are you replacing them? Our RC shows them as it was before.
It looks like I was using unpopular Unicode digit emojis, which are poorly supported on most devices. I'm fixing this.

**Comment by drygdryg** [comment]
> Why are you replacing them? Our RC shows them as it was before.

I returned the number emoji as they were and added the missing numbers.

**Review by HerHde — APPROVED** [review]
Great stuff, thank you!

**Pull request merged**
